[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
anchor_todo_list1 = "BAxXaiartNHmbeDvXLaqCWGUUGvAxtv22FZwbVjGAMku"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/giftea/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
